"""
配置参数信息
"""
Config={
    "model_path":"model_output/",
    "schema_path":"data/schema.json",
    "train_data_path":"data/train.json",
    "valid_data_path":"data/valid.json",
    "vocab_path":"../vocab.txt",
    "max_length":20,
    "hidden_size":128,
    "epoch":100,
    "batch_size":32,
    "epoch_data_size":200,#每轮训练的采样数量
    "positive_sample_rate":0.5,
    "optimizer":"adam",
    "learning_rate":1e-3,
}